services:
  - type: web
    name: payswift-main
    env: node
    region: oregon
    plan: free
    repo: https://github.com/sudeepbhagat11/PaySwift
    branch: main
    buildCommand: |
      npm install &&
      npm run prisma:generate &&
      npm run build &&
      cd bank-webhook &&
      npm install &&
      npm run prisma:generate &&
      npm run build
    startCommand: npm start
